export { default as Actors } from './Actors/actors';
export { default as MovieInformation } from './MovieInformation/MovieInformation';
export { default as Movies } from './Movies/Movies';
export { default as NavBar } from './NavBar/NavBar';
export { default as Profile } from './Profile/Profile';
export { default as Sidebar } from './Sidebar/Sidebar';
export { default as MovieList } from './MovieList/MoviesList.jsx';
export { default as Search } from './Search/Search';
export { default as Pagination } from './Pagination/Pagination';
